jobs:
  - job: ubuntu16
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install liblua5.1-dev libluabind-dev libcpptest-dev -y
        sudo apt-get install libogg-dev libvorbis-dev libopenal-dev -y
        sudo apt-get install libgif-dev libfreetype6-dev -y
        sudo apt-get install libxml2-dev -y
      displayName: 'Dependencies'
    - script: |
        mkdir build
        cmake --version
        cd build
        cmake -DWITH_NEL_TESTS=ON -DWITH_NEL_SAMPLES=ON -DWITH_LUA51=ON -DWITH_RYZOM_SERVER=ON -DWITH_RYZOM_TOOLS=ON -DWITH_NEL_TOOLS=ON ../code
        cat build/CMakeCache.txt
      displayName: 'CMake'
    - script: |
        make -j`nproc`
      displayName: 'Make'